import React,{useEffect,useRef,useState} from 'react';
import {House, Sofa, BedDouble, CookingPot, Armchair, Bath, DoorOpen, LayoutGrid, Scan, Plus, Minus, RotateCcw, Move, Mouse, ChevronRight, ArrowUpRight, X, Sun, Moon, Layers, Maximize, Info, Menu, BookOpen, Footprints, Crosshair, Eye, Camera, Table2, Flower2} from 'lucide-react';
import {rooms,getRoom,materialNames} from './data.js';
import {createWorld} from './world.js';
const icons={sofa:Sofa,bed:BedDouble,kitchen:CookingPot,dining:Table2,study:Armchair,bath:Bath,balcony:Flower2,entry:DoorOpen};
function Icon({name,...props}){const I=icons[name]||House;return <I size={19} strokeWidth={1.45} {...props}/>}
function Toggle({checked,onChange,label}){return <button className={'switch '+(checked?'on':'')} role="switch" aria-checked={checked} aria-label={label} onClick={onChange}><span/></button>}
function Segment({options,value,onChange,label}){return <div className="segment" role="group" aria-label={label}>{options.map(o=><button key={o.id} className={value===o.id?'active':''} aria-pressed={value===o.id} onClick={()=>onChange(o.id)}>{o.icon}{o.name}</button>)}</div>}
function Viewport({api,onSelect,onReady}){const ref=useRef(null);useEffect(()=>{let w;try{w=createWorld(ref.current,onSelect);api.current=w;onReady(true);}catch(e){console.error(e);onReady(false);}return()=>w?.dispose();},[]);return <div ref={ref} className="viewport" aria-label="可交互的三维户型模型"/>}
export default function App(){
 const api=useRef();const [ready,setReady]=useState(null),[selected,setSelected]=useState(null),[object,setObject]=useState(null),[mode,setMode]=useState('real'),[night,setNight]=useState(false),[furniture,setFurniture]=useState(true),[plan,setPlan]=useState(false),[inside,setInside]=useState(false),[labels,setLabels]=useState(true),[archive,setArchive]=useState(false),[menu,setMenu]=useState(false),[help,setHelp]=useState(false),[collapsed,setCollapsed]=useState(false),[explain,setExplain]=useState(false);
 const beforePlan=useRef('real');const room=getRoom(selected)||rooms[0];
 const select=(id,obj=null)=>{setSelected(id);setObject(obj);setMenu(false);if(api.current){api.current.select(id,obj?.id);if(!obj)api.current.focus(id,inside);}};
 const clickSelect=(id,obj)=>{setSelected(id);setObject(obj||null);};
 const overview=()=>{setMenu(false);setSelected(null);setObject(null);setInside(false);setPlan(false);if(plan){setMode(beforePlan.current);api.current?.setMode(beforePlan.current);}api.current?.setPlan(false);api.current?.select(null);api.current?.overview();};
 const changeMode=m=>{setMode(m);api.current?.setMode(m);};
 const changePlan=()=>{const next=!plan;setPlan(next);setInside(false);if(next){beforePlan.current=mode;setMode('wire');api.current?.setMode('wire');}else{setMode(beforePlan.current);api.current?.setMode(beforePlan.current);}api.current?.setPlan(next);};
 const enter=()=>{setSelected(room.id);setObject(null);setPlan(false);setInside(true);api.current?.setPlan(false);if(mode==='wire'){changeMode('real');}api.current?.select(room.id);api.current?.focus(room.id,true);};
 useEffect(()=>{const f=e=>{if(e.key==='Escape'){setHelp(false);setArchive(false);if(inside)overview();}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f);},[inside]);
 return <div className={'app '+(night?'night':'')+(collapsed?' collapsed':'')}>
 <header><div className="brand"><span className="brand-cn">栖居</span><span>HABITAT</span></div><nav><button className={!archive?'active':''} onClick={()=>setArchive(false)}>空间探索</button><button className={archive?'active':''} onClick={()=>setArchive(true)}>户型档案</button></nav><div className="header-actions"><button className={'outline '+(plan?'chosen':'')} onClick={changePlan}><LayoutGrid size={17}/>{plan?'返回 3D':'平面图'}</button><button className="primary" onClick={overview}><House size={17}/>全屋概览</button></div></header>
 <div className="workspace"><aside className={'directory '+(menu?'mobile-open':'')}><div className="sidebar-title"><h2>空间目录</h2><button className="icon-button" aria-label="收起空间目录" onClick={()=>{if(window.innerWidth<=600)setMenu(false);else setCollapsed(!collapsed)}}><ChevronRight size={17}/></button></div><p className="subtle">四室 · 两厅 · 三卫</p><button className={'room-row overview '+(!selected?'selected':'')} onClick={overview}><House size={19} strokeWidth={1.5}/><span>全屋概览</span></button><div className="room-list">{rooms.map(r=><button className={'room-row '+(selected===r.id?'selected':'')} key={r.id} onClick={()=>select(r.id)}><Icon name={r.icon}/><span>{r.name}</span><span className="room-area">{r.id==='dining'?'共享':r.area+' ㎡'}</span></button>)}</div><div className="sidebar-foot"><div className="status-dot"/>依据参考户型重建<small>开放顶面 · 可交互空间</small></div></aside>
 <main className="canvas-area"><Viewport api={api} onSelect={clickSelect} onReady={setReady}/><div className="canvas-title"><button className="mobile-menu icon-button" aria-label="打开空间目录" onClick={()=>setMenu(!menu)}><Menu size={20}/></button><div><h1>{inside?room.name+' · 室内漫游':plan?'居住的秩序':'光与木的日常'}</h1><p>{inside?'拖动环顾 · W A S D 移动 · Esc 返回':plan?'正交俯视 · 点击房间探索':'参考户型 · 自由探索'}</p></div></div><div className="material-control"><Segment label="模型显示模式" value={mode} onChange={changeMode} options={[{id:'real',name:'真实材质'},{id:'white',name:'白模'},{id:'wire',name:'线框'}]}/></div><div className="canvas-right"><button className={'icon-button '+(labels?'enabled':'')} title="房间标签" aria-label="切换房间标签" aria-pressed={labels} onClick={()=>{setLabels(!labels);api.current?.setLabels(!labels)}}><Layers size={18}/></button><button className="icon-button" title="操作指南" aria-label="操作指南" onClick={()=>setHelp(true)}><Info size={18}/></button></div>
 {ready===null&&<div className="load-state"><div className="loader"/>正在构建你的空间…</div>}{ready===false&&<div className="load-state">无法启动 3D 渲染，请使用支持 WebGL 2 的浏览器并启用硬件加速。</div>}
 {inside&&<button className="exit-room" onClick={overview}><ArrowUpRight size={16}/>退出房间</button>}
 <button className="mobile-explain" onClick={()=>setExplain(true)}><BookOpen size={14}/>{object?'家具讲解':'空间讲解'}</button><div className="compass"><span>N</span><svg viewBox="0 0 50 50"><path d="M25 6L18 35L25 29L32 35Z" fill="currentColor"/></svg></div>
 <div className="canvas-tools"><button title="旋转模型" aria-label="旋转模型" onClick={()=>api.current?.rotate()}><Move size={20}/><span>{inside?'环顾空间':'旋转视角'}</span></button><i/><button title="放大" aria-label="放大" onClick={()=>api.current?.zoom(.8)}><Plus size={19}/></button><button title="缩小" aria-label="缩小" onClick={()=>api.current?.zoom(1.25)}><Minus size={19}/></button><i/><button title="重置视角" aria-label="重置视角" onClick={()=>{if(inside)api.current?.focus(room.id,true);else if(plan)api.current?.setPlan(true);else api.current?.overview();}}><Crosshair size={20}/><span>重置视角</span></button></div>
 <div className="canvas-footer"><span><Mouse size={14}/>拖动旋转<span className="dot-sep">·</span>滚轮缩放<span className="dot-sep">·</span>点击探索</span><span>{plan?'2D / 正交视图':inside?'3D / 室内视角':'3D / 透视视图'}</span></div></main>
 <aside className="inspector"><div className="inspector-title"><h2>{object?'家具详情':selected?'空间详情':'空间概览'}</h2>{object?<button className="icon-button" aria-label="关闭家具详情" onClick={()=>{setObject(null);api.current?.select(selected)}}><X size={17}/></button>:<span className="tiny-number">{String(rooms.indexOf(room)+1).padStart(2,'0')} / 12</span>}</div><div className="room-detail" key={object?.id||room.id}>
 {object?<><div className="object-icon"><Icon name={room.icon}/></div><h3>{object.name}</h3><p className="english">{room.name} / 家具探索</p><p className="description">{object.description}</p><div className="object-spec"><span>材质</span><strong>{object.material}</strong></div>{!object.id.startsWith('material-')&&<button className="text-action" onClick={()=>{setInside(false);setPlan(false);api.current?.focusObject(object.id)}}><Scan size={15}/>近距离查看</button>}</>:<><div className="area-value">{room.area}<span>m²</span></div><h3>{selected?room.name:'客餐厅'}</h3><p className="english">{room.areaNote||room.en}</p><p className="description">{room.description}</p></>}
 </div><section className="materials"><h4>材质搭配</h4><div className="swatches">{materialNames.map((m,i)=><button key={m} className={'swatch s'+i} title={m} aria-label={m} onClick={()=>{setObject({id:'material-'+i,name:m,description:['浅色橡木以细密木纹连接全屋地面与柜体，带来温和、自然的空间基调。','米白亚麻用于沙发与床品，细微的织物纹理为硬朗的建筑线条增加柔软触感。','浅色石材用于台面与小件家具，细致纹理和哑光表面适配柔和照明。','鼠尾草绿点缀靠枕、座椅与软装，与木材、米白和植物形成安静的配色。'][i],material:m});}}/>)}</div></section><section className="setting-line"><span>家具显示</span><Toggle checked={furniture} label="家具显示" onChange={()=>{setFurniture(!furniture);if(furniture){setObject(null);api.current?.select(selected);}api.current?.setFurniture(!furniture)}}/></section><section className="environment"><h4>昼夜环境</h4><Segment label="昼夜环境" value={night?'night':'day'} onChange={v=>{setNight(v==='night');api.current?.setNight(v==='night')}} options={[{id:'day',name:'日间',icon:<Sun size={15}/>},{id:'night',name:'夜晚',icon:<Moon size={15}/>}]} />{night&&<p className="light-note"><span className="status-dot"/>室内灯光已自动开启</p>}</section><button className="primary enter" onClick={inside?overview:enter}><DoorOpen size={18}/>{inside?'返回全屋':'进入房间'}<ArrowUpRight size={17}/></button><p className="inspector-hint">{object?'点击模型中的其他家具，继续探索':'每个空间，都有自己的故事。'}</p></aside></div>
 {explain&&<div className="modal-backdrop" onClick={()=>setExplain(false)}><div className="modal help" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" aria-label="关闭讲解" onClick={()=>setExplain(false)}><X/></button><h2>{object?.name||room.name}</h2><p>{object?.description||room.description}</p><p>{object?object.material:room.area+' ㎡ · '+(room.areaNote||room.en)}</p><button className="primary" onClick={()=>{setExplain(false);enter()}}>进入这个房间<ArrowUpRight size={16}/></button></div></div>}{archive&&<div className="modal-backdrop" onClick={()=>setArchive(false)}><div className="modal archive" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" aria-label="关闭户型档案" onClick={()=>setArchive(false)}><X/></button><h2>户型档案</h2><p>依据提供的平面图重建 · 开放顶面住宅</p><img src="./floorplan-reference.png" alt="用户提供的原始户型图，含各房间尺寸和面积"/><div className="archive-note">保留原图空间关系及标注面积。客厅与餐厅共享 48.2 ㎡；书房计入四室。家具、门窗高度与材质为设计演示，非施工测绘数据。</div><button className="primary" onClick={()=>{setArchive(false);if(!plan)changePlan()}}>查看交互平面图<ArrowUpRight size={16}/></button></div></div>}
 {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><div className="modal help" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" aria-label="关闭操作指南" onClick={()=>setHelp(false)}><X/></button><h2>自在探索每个角落</h2><p>鼠标左键拖动旋转，右键拖动平移，滚轮缩放。触屏单指旋转，双指缩放和平移。</p><p>点击地面或左侧目录选择房间，点击家具查看说明。「进入房间」切换至人眼高度；拖动环顾，W / A / S / D 或方向键移动，Esc 返回全屋。触屏可使用画面内方向键。</p><p>「平面图」自动启用线框与正交俯视；返回 3D 时恢复之前的材质模式。</p><button className="primary" onClick={()=>setHelp(false)}>开始探索</button></div></div>}
 </div>
}
