import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {rooms,getRoom} from './data.js';
import {center,toPlan,outlinePx,wallsPx,windowsPx,doorsPx,containsPoint} from './plan.js';

// The plan uses metres; X is east, Z is south, Y is height. No ceilings are created.
const C=new THREE.Vector3(center[0],0,center[1]);
const WALL_HEIGHT=3,DOOR_HEIGHT=2.85,WINDOW_TOP=2.85;
const isTiled=id=>id==='kitchen'||id.startsWith('bath');
export function createWorld(container,onSelect){
 const scene=new THREE.Scene();scene.background=new THREE.Color('#f3f3ef');
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;container.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D 户型：拖动旋转，点击房间或家具查看讲解');
 const camera=new THREE.PerspectiveCamera(38,1,.04,150);camera.position.set(1.8,19.3,23.2);
 const ortho=new THREE.OrthographicCamera(-10,10,10,-10,.1,100);ortho.position.set(0,40,0);ortho.up.set(0,0,-1);ortho.lookAt(0,0,0);
 let activeCamera=camera;
 const composer=new EffectComposer(renderer);composer.renderTarget1.samples=4;composer.renderTarget2.samples=4;const renderPass=new RenderPass(scene,camera);const ao=new SSAOPass(scene,camera,512,512,16);ao.kernelRadius=.45;ao.minDistance=.002;ao.maxDistance=.07;composer.addPass(renderPass);composer.addPass(ao);composer.addPass(new OutputPass());
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.085;controls.minDistance=2;controls.maxDistance=45;controls.maxPolarAngle=Math.PI*.475;controls.target.set(0,0,0);
 const house=new THREE.Group();house.position.copy(C).multiplyScalar(-1);scene.add(house);
 const architecture=new THREE.Group(),furnishings=new THREE.Group();house.add(architecture,furnishings);
 const meshes=[],objects=new Map(),floorMeshes=[],lights=[],glows=[],windows=[],wallMeshes=[];let seed=37;const rand=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};
 const geoCache=new Map();const textures=[];
 function texture(kind){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=512;const ctx=canvas.getContext('2d');
 if(kind==='wood'||kind==='floor'){ctx.fillStyle=kind==='floor'?'#c9b99f':'#bba78a';ctx.fillRect(0,0,512,512);const rows=kind==='floor'?12:7;for(let row=0;row<rows;row++){const h=512/rows;ctx.fillStyle=`rgba(${130+rand()*55},${105+rand()*40},${72+rand()*40},.22)`;ctx.fillRect(0,row*h,512,h);if(kind==='floor'){ctx.strokeStyle='rgba(61,43,26,.19)';ctx.lineWidth=1;ctx.strokeRect(0,row*h,512,h);ctx.beginPath();const x=rand()*400;ctx.moveTo(x,row*h);ctx.lineTo(x,(row+1)*h);ctx.stroke();}for(let j=0;j<45;j++){ctx.strokeStyle=`rgba(65,42,21,${rand()*.13})`;ctx.lineWidth=rand()*.7+.2;ctx.beginPath();let y=row*h+rand()*h;ctx.moveTo(0,y);for(let x=0;x<=512;x+=16){ctx.lineTo(x,y+Math.sin(x*.026+j)*1.2);}ctx.stroke();}}}
 if(kind==='fabric'){ctx.fillStyle='#e5dfd2';ctx.fillRect(0,0,512,512);for(let i=0;i<512;i+=2){ctx.strokeStyle=i%4?'#ded8cc':'#efe9dc';ctx.lineWidth=.6;ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,512);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(512,i);ctx.stroke();}}
 if(kind==='stone'){ctx.fillStyle='#d6d3cb';ctx.fillRect(0,0,512,512);for(let i=0;i<6500;i++){const g=100+rand()*100;ctx.fillStyle=`rgba(${g},${g},${g},.10)`;ctx.fillRect(rand()*512,rand()*512,rand()*2+1,rand()*2+1);}for(let j=0;j<12;j++){ctx.strokeStyle='rgba(90,93,89,.12)';ctx.lineWidth=rand()*2+1;ctx.beginPath();let y=rand()*512;ctx.moveTo(0,y);for(let x=0;x<512;x+=12){y+=(rand()-.4)*12;ctx.lineTo(x,y);}ctx.stroke();}}
 const t=new THREE.CanvasTexture(canvas);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=renderer.capabilities.getMaxAnisotropy();textures.push(t);return t;}
 const woodTex=texture('wood'),floorTex=texture('floor'),fabricTex=texture('fabric'),stoneTex=texture('stone');floorTex.repeat.set(.35,.35);fabricTex.repeat.set(3,3);
 const mat=(color,roughness=.7,extra={})=>new THREE.MeshStandardMaterial({color,roughness,...extra});
 const M={wall:mat('#eeece5'),trim:mat('#faf9f3'),wood:mat('#e9dfcf',.7,{map:woodTex}),darkWood:mat('#c0ab8b',.6,{map:woodTex}),floor:mat('#f0e7d9',.8,{map:floorTex}),fabric:mat('#eee8db',.94,{map:fabricTex,bumpMap:fabricTex,bumpScale:.012}),green:mat('#7b8565',.92,{bumpMap:fabricTex,bumpScale:.013}),blanket:mat('#c6c5b3',1,{map:fabricTex}),stone:mat('#ebe7dc',.5,{map:stoneTex}),tile:mat('#a9aba5',.8,{map:stoneTex}),metal:mat('#434941',.35,{metalness:.7}),gold:mat('#b6a17a',.35,{metalness:.55}),white:mat('#fcfbf6',.28),black:mat('#202924',.3),leaf:mat('#63784a',.8),leafLight:mat('#829163',.8),terra:mat('#bfad93'),glass:new THREE.MeshStandardMaterial({color:'#c2d5d5',roughness:.12,metalness:.1,transparent:true,opacity:.2,depthWrite:false}),water:mat('#8d9e9b',.1,{metalness:.7}),screen:mat('#243330',.18),rug:mat('#b6af9e',1,{map:fabricTex}),book:mat('#d3ccbc')};
 const whiteMat=mat('#f1f0ea',.82),wireMat=new THREE.MeshBasicMaterial({color:'#809080',transparent:true,opacity:.025,depthWrite:false,wireframe:false});const edgeMat=new THREE.LineBasicMaterial({color:'#596f61',transparent:true,opacity:.7});
 function addMesh(g,m,x,y,z,parent){const mesh=new THREE.Mesh(g,m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData.original=m;parent.add(mesh);meshes.push(mesh);return mesh;}
 function box(w,h,d,x,y,z,m,parent=architecture,r=.012){let key=[w,h,d,r].join('/');let g=geoCache.get(key);if(!g){g=r?new RoundedBoxGeometry(w,h,d,2,Math.min(r,w/3,h/3,d/3)):new THREE.BoxGeometry(w,h,d);geoCache.set(key,g);}return addMesh(g,m,x,y,z,parent);}
 function cylinder(rt,rb,h,x,y,z,m,parent=architecture,n=24){const key=`c/${rt}/${rb}/${h}/${n}`;let g=geoCache.get(key);if(!g){g=new THREE.CylinderGeometry(rt,rb,h,n);geoCache.set(key,g);}return addMesh(g,m,x,y,z,parent);}
 function sphere(rx,ry,rz,x,y,z,m,parent){let g=geoCache.get('sphere');if(!g){g=new THREE.SphereGeometry(1,16,10);geoCache.set('sphere',g);}let q=addMesh(g,m,x,y,z,parent);q.scale.set(rx,ry,rz);return q;}
 function rod(a,b,r,m,parent){const av=new THREE.Vector3(...a),bv=new THREE.Vector3(...b),v=bv.clone().sub(av);const q=cylinder(r,r,v.length(),...av.clone().add(bv).multiplyScalar(.5).toArray(),m,parent,10);q.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.normalize());return q;}
 function item(room,name,description,material,x,z,angle=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=angle;g.userData={id:'f'+objects.size,room,name,description,material};objects.set(g.userData.id,g);furnishings.add(g);return g;}
 // Trace-derived floor polygons share exact wall boundaries; floor seams do not become wire walls.
 function planShape(points){const shape=new THREE.Shape();points.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();return shape;}
 function slab(points,depth,y,m,room){const q=addMesh(new THREE.ExtrudeGeometry(planShape(points),{depth,bevelEnabled:false}),m,0,y,0,architecture);q.rotation.x=-Math.PI/2;q.userData.skipWire=true;q.userData.floor=!!room;q.userData.room=room;return q;}
 slab(outlinePx.map(toPlan),.22,-.38,M.trim);
 for(const r of rooms)floorMeshes.push(slab(r.polygon,.16,-.16,isTiled(r.id)?M.tile:M.floor,r.id));
 const planArcs=new THREE.Group();house.add(planArcs);planArcs.visible=false;
 function segment(a,b){const [x1,z1]=toPlan(a),[x2,z2]=toPlan(b);const length=Math.hypot(x2-x1,z2-z1);const group=new THREE.Group();group.position.set(x1,0,z1);group.rotation.y=-Math.atan2(z2-z1,x2-x1);architecture.add(group);return{group,length,x1,z1,angle:Math.atan2(z2-z1,x2-x1)};}
 for(const [x1,z1,x2,z2,thickness] of wallsPx){const{group:g,length:len}=segment([x1,z1],[x2,z2]);const q=box(len,WALL_HEIGHT,thickness,len/2,WALL_HEIGHT/2,0,M.wall,g,.003);q.userData.wallHeight=WALL_HEIGHT;wallMeshes.push(q);box(len,.075,thickness+.016,len/2,.038,0,M.trim,g,.003);}
 for(const def of windowsPx){const{group:g,length:len}=segment(def.a,def.b);g.name=def.id;const h=WINDOW_TOP,sill=def.sill;box(len,WALL_HEIGHT-h,.14,len/2,(WALL_HEIGHT+h)/2,0,M.wall,g,.003).userData.overhead=true;box(len,sill,.14,len/2,sill/2,0,M.wall,g,.003);box(len+.02,.04,.19,len/2,sill+.02,0,M.stone,g,.003);const n=Math.max(1,Math.round(len/(def.enclosure?1.2:1.0))),frame=def.enclosure?.045:.035;
  for(let i=0;i<=n;i++)box(frame,h-sill,.07,i*len/n,(h+sill)/2,0,M.metal,g,.002);
  for(const y of[sill+.04,h-.025])box(len,.045,.07,len/2,y,0,M.metal,g,.002);
  if(def.enclosure)box(len,.028,.045,len/2,1.1,0,M.metal,g,.002);
  for(let i=0;i<n;i++)windows.push(box(len/n-frame,h-sill-.08,.014,(i+.5)*len/n,(h+sill)/2,0,M.glass,g,0));
 }
 function framedPanel(g,x,z,width,height,opaque=false){const edge=.027;box(width-2*edge,height-.1,.016,x,height/2,z,opaque?M.wood:M.glass,g,0);for(const dx of[-width/2,width/2])box(edge,height,.035,x+dx,height/2,z,M.metal,g,.002);for(const y of[.035,height-.015])box(width,.035,.035,x,y,z,M.metal,g,.002);box(.018,.22,.045,x+width/2-.07,1.0,z+.025,M.metal,g,.003);}
 for(const def of doorsPx){const{group:g,length:len,x1,z1,angle}=segment(def.a,def.b);g.name=def.name;g.userData.doorType=def.type;box(len,.10,.10,len/2,2.95,0,M.wall,g,.003).userData.overhead=true;
  if(def.type==='sliding'){
   const h=DOOR_HEIGHT,trackLength=def.pocket?len*2:len;
   for(const z of[-.04,.04]){box(trackLength,.015,.017,trackLength/2,.012,z,M.metal,g,.001);box(trackLength,.04,.018,trackLength/2,h+.035,z,M.metal,g,.001);}
   for(const x of[0,len])box(.035,h,.10,x,h/2,0,M.trim,g,.002);
   if(def.pocket)framedPanel(g,len*1.1,.06,len+.035,h,def.opaque);
   else {const n=def.panels,width=len/n+.025;for(let i=0;i<n;i++){let x=(i+.5)*len/n;if(n===4)x=i<2?(i*.48+.5)*len/n:len-((3-i)*.48+.5)*len/n;else if(i===1)x-=len*.20;framedPanel(g,x,i%2?.04:-.04,width,h,def.opaque);}}
  }else{
   for(const x of[0,len])box(.045,DOOR_HEIGHT+.05,.13,x,(DOOR_HEIGHT+.05)/2,0,M.trim,g,.003);
   const leaf=new THREE.Group();leaf.rotation.y=-def.swing;g.add(leaf);box(len-.035,DOOR_HEIGHT,.038,len/2,DOOR_HEIGHT/2,0,M.wood,leaf,.006);box(.025,.13,.065,len-.12,1,.037,M.gold,leaf,.003);
   const pts=[];for(let i=0;i<=32;i++){const theta=angle+def.swing*i/32;pts.push(new THREE.Vector3(x1+len*Math.cos(theta),.045,z1+len*Math.sin(theta)));}planArcs.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),edgeMat));
  }
 }
 // Tile joints remain finish details and are hidden from the structural wire view.
 for(const r of rooms.filter(r=>isTiled(r.id))){let[a,b,c,d]=r.box;for(let x=a+.5;x<c;x+=.5)box(.005,.003,d-b,x,.003,(b+d)/2,M.trim,architecture,0).userData.skipWire=true;for(let z=b+.5;z<d;z+=.5)box(c-a,.003,.005,(a+c)/2,.003,z,M.trim,architecture,0).userData.skipWire=true;}
 function plant(room,x,z,size=1){let g=item(room,'室内绿植','高低错落的叶片柔化建筑线条。盆栽布置在采光较好的窗边与空间转角，为家中增添自然层次。','陶盆 / 常绿叶片',x,z);cylinder(.18*size,.13*size,.34*size,0,.17*size,0,M.terra,g);cylinder(.16*size,.16*size,.025,0,.35*size,0,M.darkWood,g);for(let k=0;k<9;k++){const a=k*2.4,l=(.3+rand()*.2)*size,y=(.45+rand()*.45)*size;rod([0,.33*size,0],[Math.cos(a)*l*.45,y,Math.sin(a)*l*.45],.012*size,M.leaf,g);let leaf=sphere(.09*size,.25*size,.027*size,Math.cos(a)*l*.64,y,Math.sin(a)*l*.64,k%2?M.leaf:M.leafLight,g);leaf.rotation.set(.3,a,.5);}return g;}
 function books(g,x,y,z,n=5){for(let i=0;i<n;i++){const m=[M.book,M.green,M.darkWood,M.stone][i%4];box(.055,.21+rand()*.075,.15,x+i*.06,y+.12,z,m,g,.002);}}
 function vase(g,x,y,z,s=.12){cylinder(s*.55,s*.8,s*1.8,x,y+s*.9,z,M.white,g);cylinder(s*.65,s*.5,.02,x,y+s*1.8,z,M.gold,g);for(let i=0;i<4;i++){let a=i*2.2;rod([x,y+s*1.8,z],[x+Math.cos(a)*s,y+s*3.8,z+Math.sin(a)*s],.007,M.leaf,g);sphere(.06,.1,.025,x+Math.cos(a)*s,y+s*3.7,z+Math.sin(a)*s,M.leaf,g);}}
 function lamp(g,x,z,y=.55){cylinder(.11,.13,.035,x,y,z,M.gold,g);cylinder(.017,.017,.26,x,y+.14,z,M.gold,g);let glow=mat('#f1e4c9',.8,{emissive:'#ffc57d',emissiveIntensity:0});cylinder(.105,.16,.20,x,y+.35,z,glow,g);glows.push(glow);}
 function bedside(room,x,z){const g=item(room,'床头边柜与阅读灯','双层木质边柜收纳睡前读物，暖色阅读灯提供柔和的局部照明。夜间自动点亮。','橡木 / 黄铜 / 亚麻灯罩',x,z);box(.48,.48,.45,0,.27,0,M.wood,g,.018);box(.42,.19,.02,0,.35,.233,M.darkWood,g);box(.1,.018,.02,0,.37,.25,M.gold,g);lamp(g,0,0,.53);return g;}
 function bed(room,x,z,w=1.65,angle=0){const g=item(room,'棉麻软包双人床','低重心床架搭配柔软床头。床垫、枕头、被褥和床尾毯分层建模，棉麻织物营造松弛的休憩氛围。','橡木床架 / 棉麻床品',x,z,angle);box(w+.15,.30,2.16,0,.25,0,M.wood,g,.045);box(w,.24,2.05,0,.51,0,M.fabric,g,.10);box(w+.15,1.02,.15,0,.64,-1.05,M.blanket,g,.075);for(let i=-1;i<=1;i+=2){let p=box(w*.41,.17,.44,i*w*.24,.72,-.68,M.fabric,g,.08);p.rotation.y=i*.06;box(w*.37,.16,.30,i*w*.24,.8,-.86,M.fabric,g,.06);}box(w-.025,.13,1.15,0,.70,.35,M.fabric,g,.05);box(w+.025,.10,.70,0,.80,.62,M.blanket,g,.035);for(let i=0;i<13;i++){box(.012,.008,.65,-w/2+.06+i*w/13,.857,.62,M.fabric,g,.003);}for(let i=-1;i<=1;i+=2){box(.07,.12,.07,i*(w/2-.12),.06,.82,M.darkWood,g);}return g;}
 function wardrobe(room,x,z,w,angle=0){const g=item(room,'通顶木纹衣柜','分格柜门与细长拉手保持简洁秩序。衣柜布置沿墙，给床侧留下活动空间。','橡木饰面 / 金属拉手',x,z,angle);box(w,2.27,.55,0,1.14,0,M.wood,g,.012);for(let i=0;i<Math.round(w/.5);i++){const n=Math.round(w/.5),xx=-w/2+(i+.5)*w/n;box(w/n-.025,2.2,.025,xx,1.14,.29,M.darkWood,g,.005);box(.012,.35,.035,xx+w/n*.3,1.11,.32,M.gold,g,.002);}return g;}
 function rug(room,x,z,w,d){let g=item(room,'平织地毯','低绒平织纹理划定休息区域，柔和中性色将家具组合成完整的空间。','羊毛混纺',x,z);box(w,.025,d,0,.035,0,M.rug,g,.01);for(let i=0;i<6;i++){box(w-.12,.003,.012,0,.052,-d/2+.06+i*.018,M.fabric,g,0);box(w-.12,.003,.012,0,.052,d/2-.06-i*.018,M.fabric,g,0);}return g;}
 rug('master',2.1,8.0,2.95,2.65);bed('master',2.68,8.0,1.8,-Math.PI/2);bedside('master',3.45,6.76);bedside('master',3.45,9.24);wardrobe('master',.36,8.3,2.7,Math.PI/2);plant('master',3.25,10.0,.85);
 bed('bedA',1.32,1.5,1.45);bedside('bedA',2.45,.85);wardrobe('bedA',.35,1.9,1.7,Math.PI/2);
 rug('bedB',12.45,9.6,2.8,2.5);bed('bedB',12.80,9.6,1.65,-Math.PI/2);bedside('bedB',13.57,8.43);bedside('bedB',13.57,10.77);wardrobe('bedB',11.00,9.4,2.1,Math.PI/2);plant('bedB',11.25,10.82,.65);
 // Living: modular sofa, seam details, loose cushions and a layered table composition.
 rug('living',7.5,7.8,4.25,3.2);
 {let g=item('living','模块化转角沙发','米白亚麻包覆的 L 形沙发面向客厅中心。独立坐垫、滚边和鼠尾草绿靠枕带来细腻层次，转角躺位适合阅读与休息。','亚麻 / 高弹海绵 / 实木框架',7.6,7.4);
 box(3.2,.25,.96,0,.24,-.78,M.fabric,g,.09);box(3.2,.58,.23,0,.68,-1.2,M.fabric,g,.07);box(.24,.51,1.02,-1.57,.52,-.76,M.fabric,g,.075);box(.24,.5,2.5,1.57,.51,-.04,M.fabric,g,.075);box(1.02,.25,1.65,1.11,.24,.48,M.fabric,g,.08);
 for(let i=0;i<3;i++){box(.93,.18,.77,-1.04+i*1.03,.47,-.73,M.fabric,g,.065);const p=box(.88,.43,.17,-1.04+i*1.03,.73,-1.05,M.fabric,g,.065);p.rotation.x=.14;}box(.80,.18,1.3,1.10,.47,.5,M.fabric,g,.065);
 for(let i=0;i<4;i++){let p=box(.40,.39,.16,-1.1+i*.74,.71,-.9,i%2?M.green:M.blanket,g,.065);p.rotation.z=(i%2?.15:-.11);p.rotation.x=-.18;}
 for(let x of[-1.3,1.3])for(let z of[-1,1])cylinder(.035,.028,.14,x,.08,z*.67,M.darkWood,g,10);}
 {let g=item('living','洞石圆角茶几','厚薄错落的双圆茶几让动线更加柔和。洞石桌面搭配书刊、陶器与杯具，适合随手放置日常物品。','洞石 / 深色橡木',7.1,8.2);cylinder(.68,.68,.095,0,.49,0,M.stone,g,48);cylinder(.32,.36,.42,0,.23,0,M.wood,g,32);cylinder(.38,.38,.065,.80,.34,.36,M.darkWood,g,36);cylinder(.17,.20,.31,.80,.17,.36,M.darkWood,g);box(.30,.035,.23,-.15,.555,.08,M.book,g);box(.26,.022,.21,-.12,.58,.10,M.green,g);vase(g,.16,.54,-.17,.105);cylinder(.11,.11,.025,.78,.39,.33,M.stone,g);cylinder(.052,.049,.075,.78,.44,.33,M.white,g);}
 {let g=item('living','悬浮电视柜','低矮长柜保持空间开阔，深色屏幕与木色柜体形成轻盈的立面。柜面布置书籍和陶器，兼顾展示与收纳。','橡木 / 黑色玻璃',4.18,7.15,Math.PI/2);box(2.45,.30,.40,0,.34,0,M.wood,g);for(let i=-1;i<=1;i++)box(.76,.22,.012,i*.80,.35,.21,M.darkWood,g);box(1.72,.99,.055,0,1.17,-.03,M.black,g);box(1.65,.91,.008,0,1.19,.003,M.screen,g);rod([-.45,.50,0],[-.40,.71,0],.018,M.metal,g);rod([.45,.50,0],[.40,.71,0],.018,M.metal,g);vase(g,1.05,.50,0,.09);}
 function chair(room,x,z,angle=0,green=false){const g=item(room,green?'休闲扶手椅':'曲木餐椅',green?'低矮扶手与倾斜靠背形成轻松坐姿，绿色织物呼应全屋植物与软装。':'曲木椅背与软包坐垫结合，纤细实木椅腿保留餐厅的通透感。','实木 / 织物',x,z,angle);const m=green?M.green:M.fabric;for(const dx of[-.22,.22])for(const dz of[-.2,.2])rod([dx,.035,dz],[dx*.86,.45,dz*.86],.026,M.darkWood,g);box(.52,.12,.50,0,.46,0,m,g,.055);box(.52,.34,.10,0,.74,-.20,m,g,.06);for(const dx of[-.28,.28]){rod([dx,.43,0],[dx,.72,-.18],.023,M.wood,g);box(.05,.055,.43,dx,.68,-.04,M.wood,g,.024);}return g;}
 chair('living',5.7,8.95,-.42,true);plant('living',10.18,9.35,1.2);plant('living',4.35,5.3,.8);
 {let g=item('living','弧形落地灯','纤细灯杆与织物灯罩为沙发区域补充暖色局部照明，夜晚随室内灯光一同点亮。','金属 / 亚麻灯罩',9.48,6.15);cylinder(.22,.24,.055,0,.04,0,M.metal,g);rod([0,.06,0],[0,1.9,0],.021,M.metal,g);rod([0,1.9,0],[-.4,1.9,0],.021,M.metal,g);let m=mat('#f0dfbd',.7,{emissive:'#ffbe73',emissiveIntensity:0});cylinder(.20,.31,.35,-.4,1.73,0,m,g);glows.push(m);}
 {let g=item('dining','六人橡木餐桌','长方形圆角桌面容纳六人用餐，中央花器与餐具形成克制的桌面陈设。餐厅与厨房、客厅保持开放联系。','橡木 / 浅色石材',7.65,4.55);box(2.25,.10,.95,0,.77,0,M.stone,g,.09);for(const x of[-.88,.88])box(.10,.69,.68,x,.37,0,M.wood,g,.035);vase(g,0,.83,0,.12);for(const x of[-.74,.74])for(const z of[-.28,.28]){cylinder(.16,.16,.017,x,.836,z,M.white,g,32);cylinder(.11,.11,.012,x,.85,z,M.stone,g);cylinder(.047,.043,.09,x+.22,.88,z,M.glass,g,16);rod([x-.21,.845,z-.1],[x-.21,.845,z+.1],.007,M.gold,g);}}
 for(const x of[6.9,7.7,8.45]){chair('dining',x,3.78,0);chair('dining',x,5.30,Math.PI);}plant('dining',9.93,3.73,.8);
 // Kitchen appliances, separate cabinet fronts, handles, sink and cooktop.
 {let g=item('kitchen','L 形定制橱柜','沿两面墙展开的地柜构成连续操作台面。分格柜门、金属拉手与石材挡水条完整呈现厨房细节。','橡木饰面 / 石英石',8.99,.48);box(2.35,.82,.58,0,.43,0,M.wood,g);box(2.4,.07,.64,0,.89,0,M.stone,g);for(let i=0;i<5;i++){box(.445,.7,.035,-.94+i*.47,.47,.31,M.darkWood,g,.008);box(.15,.02,.025,-.94+i*.47,.69,.34,M.gold,g,.003);}box(2.4,.25,.05,0,1.04,-.27,M.stone,g);box(.59,.82,1.8,1.01,.43,1.1,M.wood,g);box(.64,.07,1.9,1.01,.89,1.05,M.stone,g);for(let i=0;i<3;i++){box(.025,.7,.51,.7,.47,.52+i*.55,M.darkWood,g);box(.025,.02,.13,.67,.68,.52+i*.55,M.gold,g);} }
 {let g=item('kitchen','不锈钢水槽','嵌入式单槽位于北向窗下。深色槽体、细边框与高弯水龙头组成日常清洗区。','拉丝不锈钢',8.85,.49);box(.72,.02,.46,0,.935,0,M.metal,g,.04);box(.62,.02,.36,0,.946,0,M.water,g,.035);rod([.1,.96,-.19],[.1,1.27,-.19],.018,M.metal,g);rod([.1,1.27,-.19],[.1,1.27,.01],.018,M.metal,g);rod([.1,1.27,.01],[.1,1.18,.01],.018,M.metal,g);}
 {let g=item('kitchen','嵌入式灶台与烤箱','四眼灶台与下置烤箱合并烹饪区。金属炉架、旋钮、玻璃炉门与抽油烟机逐一建模。','黑色玻璃 / 不锈钢',9.96,1.55);box(.55,.03,.65,0,.94,0,M.black,g);for(let x of[-.14,.14])for(let z of[-.17,.17]){cylinder(.09,.09,.03,x,.967,z,M.metal,g,20);box(.23,.02,.016,x,.99,z,M.black,g);box(.016,.02,.23,x,.99,z,M.black,g);}box(.025,.48,.53,-.33,.45,0,M.black,g);box(.026,.34,.41,-.35,.43,0,M.screen,g);rod([-.37,.69,-.19],[-.37,.69,.19],.012,M.metal,g);box(.48,.13,.72,0,1.92,0,M.metal,g);box(.27,.49,.30,.08,2.20,0,M.metal,g);}
 {let g=item('kitchen','双门冰箱','独立冷藏与冷冻分区，嵌入厨房侧边，使备餐动线紧凑完整。','哑光金属',8.20,2.74);box(.66,1.88,.64,0,.96,0,M.stone,g,.04);box(.63,1.16,.045,0,1.26,.34,M.white,g,.025);box(.63,.62,.045,0,.34,.34,M.white,g,.022);box(.025,.45,.025,-.22,1.28,.38,M.metal,g);box(.025,.22,.025,-.22,.39,.38,M.metal,g);}
 {let g=item('kitchen','备餐器具','木质砧板、陶瓷储物罐与杯具为厨房补充真实的生活细节。','橡木 / 陶瓷',7.98,.49);box(.31,.025,.24,0,.947,0,M.wood,g);cylinder(.08,.08,.17,.23,1.02,0,M.white,g);cylinder(.09,.09,.02,.23,1.115,0,M.wood,g);}
 // Study: bookshelves with individually modelled volumes and desk equipment.
 {let g=item('study','开放式书架','实木立板与分层搁板展示书籍、陶器和收纳盒。每层错落排列，让工作空间兼具秩序与生活感。','橡木 / 纸品',5.23,1.35,Math.PI/2);box(2.25,2.2,.28,0,1.13,-.08,M.wood,g);for(let y=.2;y<2.2;y+=.41){box(2.18,.04,.35,0,y,.05,M.darkWood,g);for(let x=-.98;x<.9;x+=.68)books(g,x,y+.025,.075,6);}for(let x of[-1.1,-.37,.37,1.1])box(.035,2.2,.38,x,1.13,.02,M.darkWood,g);}
 {let g=item('study','实木书桌','独立书桌配备笔记本电脑、台灯和随手书刊。桌面朝向房间中心，避免工作区与储物区互相干扰。','橡木 / 金属',6.40,1.9);box(1.3,.07,.65,0,.76,0,M.wood,g,.025);for(let x of[-.54,.54])for(let z of[-.24,.24])rod([x,.02,z],[x,.72,z],.028,M.darkWood,g);box(.38,.02,.26,0,.81,0,M.metal,g);let laptop=box(.38,.25,.014,0,.935,-.125,M.screen,g);laptop.rotation.x=-.12;box(.18,.028,.23,.41,.805,.04,M.book,g);lamp(g,-.48,-.13,.8);}
 chair('study',6.4,2.59,Math.PI,true);plant('study',7.15,.48,.7);
 function bathroom(room,x,z,w,d){
 let g=item(room,'悬浮浴室柜与台盆','木色悬浮柜搭配白色台盆，镜面延展空间。柜底留空便于清洁，细长龙头与石材台面保持简洁。','防潮木饰面 / 陶瓷 / 石材',x+w-.45,z+d-.39,Math.PI/2);box(.85,.47,.43,0,.53,0,M.wood,g);box(.92,.045,.48,0,.79,0,M.stone,g);box(.58,.11,.33,0,.85,0,M.white,g,.075);box(.45,.02,.23,0,.911,0,M.stone,g,.05);rod([.24,.83,-.13],[.24,1.02,-.13],.013,M.metal,g);rod([.24,1.02,-.13],[.1,1.02,-.13],.013,M.metal,g);box(.72,.86,.04,0,1.54,-.25,M.gold,g,.03);box(.67,.80,.045,0,1.54,-.224,M.water,g,.025);
 let t=item(room,'一体式坐便器','圆润的一体式坐便器靠墙布置，独立建模水箱、座圈和底座，保留卫浴空间的真实尺度。','釉面陶瓷',x+.42,z+d-.51);box(.36,.7,.19,0,.38,-.22,M.white,t,.055);sphere(.19,.18,.28,0,.36,.05,M.white,t);cylinder(.15,.13,.29,0,.17,.04,M.white,t);sphere(.17,.025,.255,0,.49,.05,M.stone,t);sphere(.145,.026,.225,0,.511,.05,M.white,t);box(.11,.012,.055,0,.744,-.22,M.metal,t);
 let sh=item(room,'玻璃淋浴间','通透玻璃分隔干湿区域。淋浴底盘、地漏、花洒与黑色五金细节，呈现完整的洗浴空间。','钢化玻璃 / 黑色五金 / 石材',x+.48,z+.49);box(.85,.035,.85,0,.03,0,M.stone,sh);box(.85,1.96,.012,0,1.01,.43,M.glass,sh,0);box(.025,2,.025,.425,1,.425,M.metal,sh);box(.85,.025,.025,0,2,.425,M.metal,sh);rod([-.24,.8,-.34],[-.24,1.93,-.34],.013,M.metal,sh);rod([-.24,1.93,-.34],[-.24,1.93,-.05],.013,M.metal,sh);cylinder(.115,.115,.026,-.24,1.91,-.05,M.metal,sh);box(.13,.005,.13,.12,.056,.06,M.metal,sh);rod([.24,1.01,.45],[.24,1.22,.45],.013,M.metal,sh);}
 for(const id of['bathMaster','bathA','bathB']){const[a,b,c,d]=getRoom(id).box;bathroom(id,a,b,c-a,d-b);}
 // Balcony leisure furniture and planting.
 chair('balcony',6.4,10.73,-.3);chair('balcony',8.13,10.73,.35);
 {let g=item('balcony','阳台休闲边几','轻巧的小圆桌连接两把休闲椅，在绿植环绕中放下一本书、一杯茶。','浅色石材 / 金属',7.27,10.86);cylinder(.3,.3,.05,0,.56,0,M.stone,g);cylinder(.023,.023,.51,0,.28,0,M.gold,g);cylinder(.19,.19,.035,0,.025,0,M.gold,g);cylinder(.052,.049,.09,0,.63,0,M.white,g);}
 for(let x of[4.3,4.85,9.53,10.2])plant('balcony',x,11.25,x<5?.9:1.25);plant('balcony',4.35,10.3,1.15);
 {let g=item('entry','入户收纳柜','薄型鞋柜与置物台承接归家的日常，钥匙托盘、花器与下方收纳让入口保持有序。','橡木 / 陶瓷',11.64,4.50,-Math.PI/2);box(1.2,.86,.35,0,.45,0,M.wood,g);for(let x of[-.30,.30])box(.57,.75,.02,x,.47,.19,M.darkWood,g);vase(g,.36,.91,0,.09);cylinder(.13,.13,.025,-.25,.92,0,M.stone,g);}
 {let g=item('entry','软包换鞋凳','柔软坐垫与轻盈木架方便进出时换鞋，底层开放收纳常用鞋履。','橡木 / 亚麻',10.94,5.14);box(.85,.11,.36,0,.44,0,M.fabric,g,.055);for(let x of[-.34,.34])for(let z of[-.12,.12])box(.04,.39,.04,x,.2,z,M.darkWood,g);box(.75,.03,.3,0,.12,0,M.wood,g);}
 function curtain(room,x,z,width){const g=item(room,'亚麻窗帘','垂直褶皱呈现亚麻织物的自然垂坠，收拢在窗侧，让采光与私密性之间保留选择。','亚麻 / 金属轨道',x,z);rod([-width/2,2.91,0],[width/2,2.91,0],.015,M.gold,g);for(const side of[-1,1])for(let i=0;i<7;i++){const q=cylinder(.038,.047,2.72,side*(width/2-.04-i*.055),1.49,0,M.fabric,g,10);q.scale.z=.55;}}
 curtain('bedA',1.49,.10,2.48);curtain('master',1.85,10.42,3.13);curtain('bedB',12.29,11.31,2.78);
 {const g=item('living','抽象装饰画','大地色的几何构图与细木框呼应空间材质，为客厅立面增加安静的视觉焦点。','木框 / 艺术纸',10.59,8.40,-Math.PI/2);box(1.18,.76,.04,0,1.39,0,M.darkWood,g);box(1.10,.68,.016,0,1.39,.027,M.fabric,g);box(.43,.47,.009,-.23,1.38,.042,M.terra,g);box(.35,.20,.011,.19,1.24,.043,M.green,g);cylinder(.17,.17,.014,.22,1.52,.04,M.stone,g).rotation.x=Math.PI/2;}
 // Room-level warm lights; shade materials are also emissive at night.
 const hemi=new THREE.HemisphereLight('#fff6e7','#c5c9bc',1.45);scene.add(hemi);const sun=new THREE.DirectionalLight('#fff3db',2.4);sun.position.set(-9,20,15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-13;sun.shadow.camera.right=13;sun.shadow.camera.top=13;sun.shadow.camera.bottom=-13;sun.shadow.normalBias=.025;sun.shadow.bias=-.0003;scene.add(sun);const fill=new THREE.DirectionalLight('#f4f8ff',.5);fill.position.set(8,10,-12);scene.add(fill);
 for(const r of rooms){let l=new THREE.PointLight('#ffcb8f',0,6,2);l.position.set(r.point[0]-C.x,2.2,r.point[1]-C.z);scene.add(l);lights.push(l);}
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshBasicMaterial({color:'#f3f3ef'}));ground.material.color.multiplyScalar(1.8);ground.rotation.x=-Math.PI/2;ground.position.y=-.40;ground.receiveShadow=false;scene.add(ground);const shadowGround=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.14}));shadowGround.rotation.x=-Math.PI/2;shadowGround.position.y=-.395;shadowGround.receiveShadow=true;scene.add(shadowGround);
 const labelsLayer=document.createElement('div');labelsLayer.className='room-labels';container.appendChild(labelsLayer);const labelEls=rooms.map(r=>{let el=document.createElement('button');el.className='model-label';el.innerHTML=`<span>${r.name}</span><small>${r.id==='dining'?'客餐厅共享':r.area+' ㎡'}</small>`;el.setAttribute('aria-label','选择'+r.name);el.onclick=()=>{select(r.id);focus(r.id,inside);onSelect(r.id,null);};labelsLayer.appendChild(el);return{el,r};});
 const pad=document.createElement('div');pad.className='walk-pad';pad.innerHTML='<button aria-label="向前移动" data-key="w">↑</button><div><button aria-label="向左移动" data-key="a">←</button><button aria-label="向后移动" data-key="s">↓</button><button aria-label="向右移动" data-key="d">→</button></div>';container.appendChild(pad);const keys=new Set();for(const b of pad.querySelectorAll('button')){b.onpointerdown=e=>{e.stopPropagation();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key)};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key);}
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let selected=null,selectedObject=null,mode='real',isNight=false,showFurniture=true,showLabels=true,plan=false,inside=false,yaw=Math.PI,pitch=-.08,tween=null,disposed=false,pointerStart=null,dragging=false,lastTime=0,frame;
 const selectBox=new THREE.BoxHelper(new THREE.Object3D(),'#8c9b63');selectBox.visible=false;scene.add(selectBox);
 function select(id,obj){selected=id;selectedObject=obj;for(const {el,r}of labelEls)el.classList.toggle('selected',r.id===id);if(obj&&objects.has(obj)){selectBox.setFromObject(objects.get(obj));selectBox.visible=showFurniture&&!plan;}else selectBox.visible=false;container.dataset.room=id||'all';}
 function animateTo(pos,target){tween={start:performance.now(),from:camera.position.clone(),to:pos.clone(),targetFrom:controls.target.clone(),targetTo:target.clone()};}
 function homePosition(){return new THREE.Vector3(1.8,23.5,19).normalize().multiplyScalar(Math.max(23,29/camera.aspect));} function overview(){camera.fov=38;camera.updateProjectionMatrix();inside=false;pad.classList.remove('visible');controls.enabled=!plan;controls.minDistance=2;controls.maxDistance=45;controls.maxPolarAngle=Math.PI*.475;animateTo(homePosition(),new THREE.Vector3(0,0,0));container.dataset.inside='false';}

 function focus(id,enter=false){const r=getRoom(id);if(!r)return;selected=id;inside=enter;container.dataset.inside=String(inside);pad.classList.toggle('visible',enter);const p=new THREE.Vector3(r.point[0]-C.x,.35,r.point[1]-C.z);if(plan)return;if(enter){camera.fov=68;camera.updateProjectionMatrix();controls.enabled=false;tween=null;const [pos,look]=r.viewpoint;camera.position.set(pos[0]-C.x,1.62,pos[1]-C.z);yaw=Math.atan2(-(look[0]-pos[0]),-(look[1]-pos[1]));pitch=-.26;updateLook();}else{controls.enabled=true;const size=Math.max(r.box[2]-r.box[0],r.box[3]-r.box[1]);animateTo(p.clone().add(new THREE.Vector3(.6,size*1.1+3,size*1.1+3)),p);}}
 function focusObject(id){const g=objects.get(id);if(!g)return;inside=false;plan=false;planArcs.visible=false;for(const q of meshes)if(q.userData.overhead)q.visible=true;activeCamera=camera;controls.object=camera;controls.enabled=true;pad.classList.remove('visible');const b=new THREE.Box3().setFromObject(g),p=b.getCenter(new THREE.Vector3()),s=b.getSize(new THREE.Vector3()).length();animateTo(p.clone().add(new THREE.Vector3(s*.5+1,s*.4+1,s*.7+1)),p);}
 function setMode(value){mode=value;shadowGround.visible=value!=='wire';container.dataset.mode=value;for(const q of meshes){if(!q.isMesh)continue;q.castShadow=value!=='wire';q.material=value==='real'?q.userData.original:value==='white'?whiteMat:wireMat;q.visible=!(value==='wire'&&q.userData.skipWire)&&!(plan&&q.userData.overhead);if(value==='wire'&&!q.userData.skipWire&&!q.userData.edges){let edges=new THREE.LineSegments(new THREE.EdgesGeometry(q.geometry,10),edgeMat);q.add(edges);q.userData.edges=edges;}if(q.userData.edges)q.userData.edges.visible=value==='wire';}ground.material.color.set(value==='wire'?'#eef2ed':isNight?'#222b2d':'#f3f3ef').multiplyScalar(1.8);selectBox.visible=!!selectedObject&&showFurniture&&!plan;}
 function setNight(v){isNight=v;container.dataset.night=String(v);scene.background.set(v?'#222b2d':'#f3f3ef');ground.material.color.set(v?'#222b2d':'#f3f3ef').multiplyScalar(1.8);hemi.intensity=v?.55:1.45;sun.intensity=v?.25:2.4;sun.color.set(v?'#acc4ee':'#fff3db');fill.intensity=v?.14:.5;lights.forEach(l=>l.intensity=v?13:0);glows.forEach(m=>m.emissiveIntensity=v?2.3:0);renderer.toneMappingExposure=v?1.15:1.18;}
 function setFurniture(v){showFurniture=v;furnishings.visible=v;selectBox.visible=v&&!!selectedObject&&!plan;container.dataset.furniture=String(v);}
 function setPlan(v){plan=v;planArcs.visible=v;for(const q of meshes)if(q.userData.overhead)q.visible=!v;inside=false;pad.classList.remove('visible');controls.enabled=true;controls.object=v?ortho:camera;activeCamera=v?ortho:camera;controls.enableRotate=!v;controls.minDistance=v?.1:2;controls.target.set(0,0,0);if(v){tween=null;controls.target.set(0,0,.65);ortho.position.set(0,40,.65);ortho.zoom=1;ortho.updateProjectionMatrix();ortho.lookAt(0,0,.65);}else overview();container.dataset.plan=String(v);}
 function setLabels(v){showLabels=v;}
 function updateLook(){camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch;camera.rotation.z=0;}
 function down(e){if(e.target!==renderer.domElement)return;pointerStart={x:e.clientX,y:e.clientY,lx:e.clientX,ly:e.clientY};dragging=false;}
 function move(e){if(inside&&pointerStart){let dx=e.clientX-pointerStart.lx,dy=e.clientY-pointerStart.ly;yaw-=dx*.004;pitch=THREE.MathUtils.clamp(pitch-dy*.004,-1.2,1.2);updateLook();pointerStart.lx=e.clientX;pointerStart.ly=e.clientY;}if(pointerStart&&Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>5)dragging=true;}
 function up(e){if(!pointerStart)return;const drag=dragging;pointerStart=null;if(drag||e.target!==renderer.domElement)return;const bounds=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-bounds.left)/bounds.width*2-1,-(e.clientY-bounds.top)/bounds.height*2+1);ray.setFromCamera(pointer,activeCamera);const hits=ray.intersectObjects([architecture,...(showFurniture?[furnishings]:[])],true).filter(h=>h.object.isMesh);for(const h of hits){let p=h.object;while(p&&p!==house){if(p.userData.id){select(p.userData.room,p.userData.id);onSelect(p.userData.room,{...p.userData});return;}p=p.parent;}if(h.object.userData.floor){const pos=house.worldToLocal(h.point.clone());const r=[...rooms].reverse().find(r=>containsPoint(r.polygon,pos.x,pos.z));if(r){select(r.id);onSelect(r.id,null);return;}}}}
 function keyDown(e){if(inside&&['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();keys.add(e.key);}}function keyUp(e){keys.delete(e.key)}function blur(){keys.clear();pointerStart=null;}
 renderer.domElement.addEventListener('pointerdown',down);window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);controls.addEventListener('start',()=>tween=null);
 function resize(){const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;renderer.setSize(w,h);composer.setSize(w,h);ao.setSize(Math.round(w*.75),Math.round(h*.75));camera.aspect=w/h;camera.updateProjectionMatrix();const extent=Math.max(9.3,8.4/(w/h));ortho.left=-extent*w/h;ortho.right=extent*w/h;ortho.top=extent;ortho.bottom=-extent;ortho.updateProjectionMatrix();if(!inside&&!selected&&!plan){tween=null;camera.position.copy(homePosition());controls.target.set(0,0,0);}}const ro=new ResizeObserver(resize);ro.observe(container);resize();
 const temp=new THREE.Vector3();function render(time){if(disposed)return;frame=requestAnimationFrame(render);let dt=Math.min((time-lastTime)/1000,.05)||.016;lastTime=time;
 if(tween&&!inside&&!plan){let t=Math.min((time-tween.start)/850,1);t=1-Math.pow(1-t,3);camera.position.lerpVectors(tween.from,tween.to,t);controls.target.lerpVectors(tween.targetFrom,tween.targetTo,t);if(t>=.999)tween=null;}
 if(inside){let forward=(keys.has('w')||keys.has('ArrowUp')?1:0)-(keys.has('s')||keys.has('ArrowDown')?1:0),right=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0);if(forward||right){let n=Math.hypot(forward,right);const dx=(-Math.sin(yaw)*forward+Math.cos(yaw)*right)*dt*1.7/n,dz=(-Math.cos(yaw)*forward-Math.sin(yaw)*right)*dt*1.7/n,r=getRoom(selected);const walkRooms=['living','balcony'].includes(selected)?[getRoom('living'),getRoom('balcony')]:[r];const valid=(x,z)=>r&&[[0,0],[.12,0],[-.12,0],[0,.12],[0,-.12]].every(([a,b])=>{const px=x+C.x+a,pz=z+C.z+b;if(!walkRooms.some(room=>containsPoint(room.polygon,px,pz)))return false;return !wallsPx.some(([ax,az,bx,bz,t])=>{const A=toPlan([ax,az]),B=toPlan([bx,bz]),dx=B[0]-A[0],dz=B[1]-A[1],u=Math.max(0,Math.min(1,((px-A[0])*dx+(pz-A[1])*dz)/(dx*dx+dz*dz)));return Math.hypot(px-A[0]-u*dx,pz-A[1]-u*dz)<t/2;});});if(valid(camera.position.x+dx,camera.position.z))camera.position.x+=dx;if(valid(camera.position.x,camera.position.z+dz))camera.position.z+=dz;}}else controls.update();
 for(const {el,r}of labelEls){const visible=showLabels&&!inside;el.style.display=visible?'':'none';if(visible){temp.set(r.point[0]-C.x,.13,r.point[1]-C.z).project(activeCamera);el.style.left=(temp.x*.5+.5)*container.clientWidth+'px';el.style.top=(-temp.y*.5+.5)*container.clientHeight+'px';el.style.visibility=temp.z<1&&Math.abs(temp.x)<.98&&Math.abs(temp.y)<.95?'visible':'hidden';el.classList.toggle('plan-label',plan);}}
 if(mode==='wire'||plan){renderer.render(scene,activeCamera);}else{renderPass.camera=activeCamera;ao.camera=activeCamera;composer.render();}}
 frame=requestAnimationFrame(render);container.dataset.meshes=String(meshes.length);container.dataset.objects=String(objects.size);container.dataset.mode='real';container.dataset.plan='false';container.dataset.furniture='true';container.dataset.night='false';
 return{select,focus,overview,focusObject,setMode,setNight,setFurniture,setPlan,setLabels,zoom(f){if(plan){ortho.zoom=THREE.MathUtils.clamp(ortho.zoom/f,.5,4);ortho.updateProjectionMatrix();}else if(inside){camera.fov=THREE.MathUtils.clamp(camera.fov*f,28,75);camera.updateProjectionMatrix();}else{tween=null;camera.position.sub(controls.target).multiplyScalar(f).add(controls.target);}},rotate(){if(inside){yaw+=Math.PI/4;updateLook();}else if(!plan){tween=null;let v=camera.position.clone().sub(controls.target);v.applyAxisAngle(new THREE.Vector3(0,1,0),Math.PI/6);camera.position.copy(v.add(controls.target));}},dispose(){disposed=true;cancelAnimationFrame(frame);ro.disconnect();controls.dispose();window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);geoCache.forEach(g=>g.dispose());textures.forEach(t=>t.dispose());scene.traverse(o=>{if(o.geometry&&!geoCache.has(o.geometry))o.geometry.dispose();});new Set([...Object.values(M),whiteMat,wireMat,edgeMat,...glows,ground.material]).forEach(m=>m.dispose());ao.dispose();composer.dispose();renderer.dispose();container.replaceChildren();}};
}
